---
sheets:
  - sheet_name: coc
    output_workbooks:
      - workbook_name: Property
        new_columns:
          - column_name: Property Premium 100%
            value_definition: X*W
        remove_totals_row: True
      - workbook_name: Liability
        remove_totals_row: True
  - sheet_name: cc
    output_workbooks:
      - workbook_name: Property
        new_columns:
          - column_name: Property Premium 100%
            value_definition: X*W
        remove_totals_row: True
      - workbook_name: Liability
        remove_totals_row: True
  - sheet_name: cgl
    remove_totals_row: True
remove_totals_row: False